# @package _group_

defaults:
  - model: null

hydra:
  run:
    dir: ${common_eval.results_path}/viterbi
  sweep:
    dir: ${common_eval.results_path}
    subdir: viterbi
task:
  _name: audio_finetuning
  data: ???
  normalize: false
  labels: ltr
decoding:
  type: viterbi
  unique_wer_file: true
  results_path: ???
  prediction_log_path: ???
common_eval:
  results_path: ???
  path: ???
  post_process: letter
dataset:
  max_tokens: 1100000
  gen_subset: ???